apiVersion: v1
kind: Namespace
metadata:
  name: kubelet-exporter
  annotations: 
    email: "petros.demetriou_at_outlook.com"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata: 
  name: kubelet-exporter
rules:
- apiGroups:
  - ""
  resources:
  - nodes/metrics
  - nodes/stats
  verbs:
  - get
- nonResourceURLs:
  - /metrics
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubelet-exporter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubelet-exporter
subjects:
- kind: ServiceAccount
  name: kubelet-exporter
  namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata: 
  name: kubelet-exporter
