apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata: 
  name: kubelet-stats-exporter
  namespace: openshift-monitoring
spec: 
  endpoints:
  - interval: 30s
    port: metrics
  namespaceSelector:
    matchNames:
    - openshift-monitoring
  selector:
    matchLabels:
      name: kubelet-stats-exporter
