apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata: 
  name: kubelet-stats-exporter
spec: 
  endpoints:
  - interval: 30s
    port: metrics
  namespaceSelector:
    matchNames:
    - monitoring
  selector:
    matchLabels:
      name: kubelet-stats-exporter